# Generated by Django 5.1 on 2024-12-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('excerpt', models.CharField(max_length=200)),
                ('img_name', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('slug', models.SlugField()),
                ('content', models.CharField(max_length=1000)),
            ],
        ),
    ]
