# Generated by Django 5.1 on 2024-12-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_author_tag_alter_posts_content_alter_posts_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='img_name',
            field=models.ImageField(upload_to='posts'),
        ),
    ]
