# Generated by Django 5.1 on 2024-12-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_posts_img_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='img_name',
            field=models.ImageField(null=True, upload_to='posts'),
        ),
    ]
